config_name: cytopipe_defaults
config_paths:
  single_cell: "configs/analysis_configs/single_cell_configs.yaml"
  annotate: "configs/analysis_configs/annotate_configs.yaml"
  normalize: "configs/analysis_configs/normalize_configs.yaml"
