config_name: cytopipe_defaults
config_paths:
  single_cell: "config/analysis_confings/single_cell_config.yaml"
  annotate: "config/analysis_confings/annotate_config.yaml"
  normalize: "config/analysis_confings/normalize_config.yaml"
