annotate_configs:
  params:
    join_on: ["Metadata_Assay_Plate_Barcode", "Image_Metadata_Plate"]
    output_file: "none"
    add_metadata_id_to_platemap: True
    format_broad_cmap: False
    clean_cellprofiler: True
    external_metadata: "none"
    external_join_left: "none"
    external_join_right: "none"
    compression_options: "gzip"
    float_format: null
    cmap_args: {}
