annotate_configs:
  params:
    join_on:
      - Metadata_well_position
      - Image_Metadata_Well
    add_metadata_id_to_platemap: True
    format_broad_cmap: False
    clean_cellprofiler: True
    external_metadata: "none"
    external_join_left: "none"
    external_join_right: "none"
    compression_options:
      method: "gzip"
      mtime: 1
    float_format: null
    cmap_args: {}

      # - Metadata_Well
# challenges
# -- compression options:
  # -- compression time changes for each gzip there github might flag changes
  # occurred in the data
  #
  # future: conpressino_options might not be in the config file. define in
  # global configs (i.e threads)