evaluate_configs:
  params:
    operation: "replicate_reproducibility"
    groupby_columns: ["Metadata_broad_sample"]
    similarity_metric: "pearson"
    replicate_reproducibility_quantile: 0.95
    replicate_reproducibility_return_median_cor: False
    precision_recall_k: 10
    grit_control_perts: ["None"]
    grit_replicate_summary_method: "mean"
    mp_value_params: {}
    enrichment_percentile: 0.99
    hitk_percent_list: [2, 5, 10]
