feature_select_configs:
  params:
    features: infer
    image_features: False
    samples: all
    operation:
      - variance_threshold
      - drop_na_columns
      - correlation_threshold
      # - blocklist This requires a blocklist file. (meeting with greg)
      - drop_outliers
    na_cutoff: 0.05
    corr_threshold: 0.9
    corr_method: pearson
    freq_cut: 0.05
    unique_cut: 0.1
    compression_options: gzip
    float_format: null
    blocklist_file: null
    outlier_cutoff: 15
    noise_removal_perturb_groups: null
    noise_removal_stdev_cutoff: null


# there is a path but snakemake is not capturing it.
# also the blocklist_file var might be wrong