feature_select_configs:
  params:
    features: infer
    image_features: False
    samples: all
    operation: variance_threshold
    na_cutoff: 0.05
    corr_threshold: 0.9
    corr_method: pearson
    freq_cut: 0.05
    unique_cut: 0.1
    compression_options: gzip
    float_format: None
    blocklist_file: None
    outlier_cutoff: 15
    noise_removal_perturb_groups: None
    noise_removal_stdev_cutoff: None
