normalize_configs:
  params:
    features: infer
    image_features: False
    meta_features: infer
    # samples: all
    samples: "Metadata_pert_name == 'EMPTY'"
    # method: standardize
    method: mad_robustize
    compression_options:
      method: gzip
      mtime: 1
    float_format: null
    mad_robustize_epsilon: 1.0e-18
    spherize_center: True
    spherize_method: ZCA-cor
    spherize_epsilon: 1.0e-6

# Notes
# -- order of different normalization methods
