single_cell_config:
  params:
    strata:
      - Image_Metadata_Plate
      - Image_Metadata_Well
    image_cols:
      - TableNumber
      - ImageNumber
      - Image_Metadata_Site
    aggregation_operation: median
    compartments:
      - cells
      - cytoplasm
      - nuclei
    compartment_linking_cols: default_linking_cols
    merge_cols:
      - TableNumber
      - ImageNumber
    add_image_features: False
    image_feature_categories: None
    features: infer
    load_image_data: True
    subsample_frac: 1
    subsample_n: all
    subsampling_random_state: none
    fields_of_view: all
    fields_of_view_feature: Metadata_Site
    object_feature: Metadata_ObjectNumber
